"""Audit the competition training file and cache it as parquet.

    uv run python scripts/audit_data.py

Reads data/raw/train.csv, writes reports/data_audit.md and data/processed/train.parquet.
"""

import json
import time
from pathlib import Path

from closing_auction.data import audit, load_train

ROOT = Path(__file__).resolve().parents[1]


def main():
    start = time.time()
    df = load_train(ROOT / "data" / "raw" / "train.csv")
    print(f"loaded {len(df):,} rows in {time.time() - start:.0f}s")

    processed = ROOT / "data" / "processed"
    processed.mkdir(parents=True, exist_ok=True)
    df.to_parquet(processed / "train.parquet", index=False)

    facts = audit(df)
    lines = ["# Data audit (generated by scripts/audit_data.py)", "",
             "Source: Kaggle, Optiver - Trading at the Close, `train.csv`.", ""]
    for key, value in facts.items():
        if isinstance(value, dict):
            lines += [f"## {key}", "", "```", json.dumps(value, indent=1, default=str), "```", ""]
        else:
            lines.append(f"- **{key}**: {value}")
    (ROOT / "reports" / "data_audit.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
